apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: argocd-configs
  annotations:
    github.com/project-slug: dzemanov/argocd-configs
spec:
  type: other
  lifecycle: unknown
  owner: user:development/guest
