# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-app-first-instance
  namespace: first
  labels:
    environment: development
    app: nginx-multiinstance
    type: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: basic-app-svc-first-instance
  namespace: first
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx-multiinstance
