# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-app
  namespace: demo-apps
  labels:
    environment: staging
    app: nginx
    type: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      securityContext:
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
      initContainers:
      - name: init-nginx
        image: nginx:1.14.2
        command: ['sh', '-c', 'mkdir -p /var/cache/nginx/client_temp /var/cache/nginx/proxy_temp /var/cache/nginx/fastcgi_temp /var/cache/nginx/uwsgi_temp /var/cache/nginx/scgi_temp /var/log/nginx && chmod -R 755 /var/cache/nginx /var/log/nginx']
        volumeMounts:
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-log
          mountPath: /var/log/nginx
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-log
          mountPath: /var/log/nginx
      volumes:
      - name: nginx-cache
        emptyDir: {}
      - name: nginx-log
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: basic-app-svc
  namespace: demo-apps
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx