# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-app
  namespace: demo-apps
  labels:
    environment: staging
    app: nginx
    type: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        fsGroup: 101
      containers:
      - name: nginx
        image: nginx:1.25-alpine
        ports:
        - containerPort: 8080
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: cache
          mountPath: /var/cache/nginx
        - name: run
          mountPath: /var/run
      volumes:
      - name: cache
        emptyDir: {}
      - name: run
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: basic-app-svc
  namespace: demo-apps
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: nginx